# Uncomment the following line to enable deep sleep
# CONFIG_ZMK_SLEEP=y

# Uncomment the following line to increase the keyboard's wireless range
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# vendor id and product id
CONFIG_USB_DEVICE_VID=0x29EA
CONFIG_USB_DEVICE_PID=0x0360
CONFIG_USB_DEVICE_SN=0x0

# Enable eager debouncing
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=1
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=10

# Enable ZMK Studio for Realtime Keymap Updates
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n

# Uncomment the following line to enable USB Logging (this increases power usage by a significant amount, turn it off when not in use)
# CONFIG_ZMK_USB_LOGGING=y
